### ISSUE TITLE
Add WardScore

### ISSUE THREAD

**Issue by irae** [2ezgg/2ezgg.github.io#64]
It's an easy link http://wardscore.loltools.net/?name=RNG%20CRBZ&region=na

Should be pretty easy to add to the sidebar, and it's such an important stats, specially for lower elo players to be looking at.

**Comment by joel1st** [comment]
Hey there: http://2ez.gg/#settings-area and click the [+] next to WardScore

**Comment by irae** [comment]
I see, just not a default.
I would think this would be a nice default. Not for everyone, but nice for the community.
